name: BuildAndTest

on:
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    
    runs-on: macos-13
    
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Build and test
      run: xcodebuild clean build -project  "Steps.xcodeproj" -scheme "Steps" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'
