name: BuildAndTest

on: [ pull_request ]

jobs:
  build-and-test:
    
    runs-on: macos-13
    
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v3
  
      - name: Run a multi-line script
        run: |
            sudo xcode-select -s /Applications/Xcode_15.0.1.app
            xcodebuild test -scheme Steps CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPad (10th generation)"
